app/urls.py
from django.urls import path

from . import views

app_name = "app"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path('signup/', views.signup, name='signup'),
    path("users/<int:pk>/", views.UserDetailView.as_view(), name="users_detail"),
    path("users/<int:pk>/update/", views.UserUpdateView.as_view(), name="users_update"),
    path('users/<int:pk>/delete/', views.UserDeleteView.as_view(), name='users_delete'),
    path("lists/create/", views.ListCreateView.as_view(), name="lists_create"),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
    path('', include("django.contrib.auth.urls")),
]

app/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class List(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
       return self.title

app/views.py
from django.shortcuts import render,redirect,resolve_url
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import DetailView,UpdateView,DeleteView,CreateView
from .form import UserForm,ListForm
from .mixins import OnlyYouMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from . models import List
# Create your views here.


def index(request):
    return render(request, "app/index.html")

def home(request):
    return render(request, "app/home.html")

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user_instance = form.save()
            login(request, user_instance)
            return redirect("app:home")
    else:
        form = UserCreationForm()

    context = {
        "form": form
    }
    return render(request, 'app/signup.html', context)
@login_required
def home(request):
    return render(request, "app/home.html")

class UserDetailView(LoginRequiredMixin,DetailView):
    model = User
    template_name = "app/users/detail.html"


class UserUpdateView(OnlyYouMixin,UpdateView):
    model = User
    template_name = "app/users/update.html"
    form_class = UserForm

    def get_success_url(self):
        return resolve_url('app:users_detail', pk=self.kwargs['pk'])

class UserDeleteView(OnlyYouMixin,DeleteView):
    model = User
    template_name = "app/users/delete.html"

    def get_success_url(self):
        return resolve_url('app:users_detail', pk=self.kwargs['pk'])

class ListCreateView(LoginRequiredMixin, CreateView):
    model = List
    template_name = "app/lists/create.html"
    form_class = ListForm
    success_url = reverse_lazy("app:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

app/templates/app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Work-Maker</title>
  </head>
  <body>
    <header>
      <nav clas="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'app:index' %}">Work-maker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target='#navbarSupportedContent'
        aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <span class="navbar-text">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app:users_detail' request.user.pk %}">{{ request.user.username }}</a>
              </li>
            </span>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
            </li>

            {% else %}
           <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">ログイン</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'app:signup' %}">サインアップ</a>
           </li>
           {% endif %}

          </ul>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/app/home.html
{% extends "app/base.html" %}

{% block content %}
<div class="conteiner">
  <h1>サインアップ完了</h1>
  <p>サインアップが完了しました。</p>
</div>
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1 class="dispaly-4">Work-Maker</h1>
  <p class="lead">Work-Makerでタスク管理をしてみましょう。</p>
  <p class="my-4">
  <p>このアプリケーションはDjangoで作られています。</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">ログイン</a>
  <a class="btn btn-primary btn-lg" href="#" role="button">サインアップ</a>
</div>
{% endblock %}

app/templates/app/lists/create.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト作成</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

app/templates/app/signup.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary">登録</button>
  </form>
</div>
{% endblock %}

app/templates/app/users/delete.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
    <h1>退会</h1>
    <form method="post">
      {% csrf_token %}
      <p>あなたのアカウント「@{{ user.username }}」を本当に削除してよろしいですか？</p>
      <button type="submit" class="btn btn-danger">削除</button>
      <a href="{% url 'app:users_detail' user.pk %}"class="btn btn-primary">キャンセル</a>
    </form>
</div>
{% endblock %}

app/templates/app/users/detail.html
 {% extends "app/base.html" %}

 {% block content %}
 <div class="container">
  <h1>ユーザー詳細</h1>
      <dl class="row">
      <dt class="col-sm-3">ユーザー名</dt>
      <dd class="col-sm-9">{{ user.username}}</dd>
      <dt class="col-sm-3">姓</dt>
      <dd class="col-sm-9">{{ user.last_name }}</dd>
      <dt class="col-sm-3">名</dt>
      <dd class="col-sm-9">{{ user.first_name }}</dd>
      <dt class="col-sm-3">メールアドレス</dt>
      <dd class="col-sm-9">{{ user.email }}</dd>
   </dl>
   {% if user.pk == request.user.pk %}
   <a class="btn btn-primary" href="{% url 'app:users_update' user.pk %}" role="button">編集</a>
   <a class="btn btn-danger" href="{% url 'app:users_delete' user.pk %}" role="button">退会</a>
   {% else %}
   <a class="btn btn-primary disabled" href="#" role="button">編集</a>
   <a class="btn btn-danger disabled" href="#" role="button">退会</a>
   {% endif %}
 </div>
  {% endblock %}

app/templates/app/users/update.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
  <h1>ユーザー編集</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</<button>
    </form>
</div>
{% endblock %}